---
title: "류경민"
output: html_document
---
```{r}
## 문제 1 

# 1) 시행횟수가 6이고 성공확률이 1/3인 이항분포에서 성공횟수가 3이 될 확률
b1 <- dbinom(3, size = 6, prob = 1/3)
b1

# 2) 평균이 170이고 표준편차가 6인 정규분포에서 상위 20%되는 사람들의 키 범위
qnorm(0.8, mean = 170, sd=6)
# 175이상

# 3) 자유도가 3인 카이제곱분포에서 누적확률이 95%일때의 값
pchisq(7.814, df=3)

# 4) 자유도가 2인 t분포에서 누적확률이 0.975일때의 값
pt(4.30, df=2)

# 5) 표준정규분포에서 확률변수의 값이 1일 떄의 누적확률
pnorm(1, mean = 0,sd=1)

```

```{r}
## 문제 2 
# 다음문항이 베르누이 시행인지 판별하세요.
#2) 전화를 한사람이 여자인지 판별하는 것은 남자와 여자일 떄의 확률로 나뉘기 떄문에 베르누이 시행임
#4)동전의 앞면이 위로가는 경우를 성공의 경우 그 외를 실패로 정의 한다면 베르누이 시행
#5)사람의 눈의 색이 다양함으로 녹색인 경우만을 성공으로 정의 한다면 베르누이 시행임


```


```{r}
## 문제 3

# iris setosa 종 Sepal.Length 의 모평균에 대한 95% 신뢰구간
library(dplyr)
i <- iris
```


```{r}
is <- i %>%
  filter(Species=="setosa") %>%
  select(Sepal.Length)

t.test(is)
# 4.9058 ~ 5.1060
```

```{r}
## 문제 4 
# 한 농구 선수가 자유투를 던지면 10번중 7번을 성공
# 1) 9/10 확률
ft <- dbinom(9, size = 10, prob = 7/10)
ft

# 2) 10번 던질때 5 <=x<= 8확률

dbinom(8, size=10, prob = 0.7)-dbinom(4, size = 10,prob = 0.7)

```

```{r}
## 문제 5 
# 2006년 조사에 의하면 한국인의 1인 1일 평균 알코올 섭취량이 8.1g 
# 2008년 무작위 알코올 섭취량 

a8 <- c(16.90,13.21, 15.67, 9.87, 13.15, 9.98, 3.56, 14.50, 8.12, 6.97)

t.test(a8, mu=8.1)

# 0.05 보다 p 값이 작다 (p-value = 0.04562) 그러므로 영가설 기각
# 달라졌다고 할수 있다. 
```

```{r}
## 문제 6번 
# 정규분포에서 form <=x<= tp 확률을 구하는 함수 
# rengenorm(from, to, mean, sd)을 작성하고 
# rengenorm(-1.96, 1.96, 0, 1) 값을 구하세요. 
rengenorm <- function(from, to, mean, sd){
  pnorm(to,mean = mean, sd=sd) - pnorm(from,mean = mean, sd=sd)
}
rengenorm(-1.96, 1.96, 0, 1)

```

```{r}
## 문제 7번 
# 1) mpg 데이터 이용 subcompact 와 midsize 자동차 도시연비 비교
library(ggplot2)
m <- mpg

ms <- m %>%
  filter(class %in% c("subcompact", "midsize"))

var.test(ms$cty ~ ms$class)
# p-value = 5.201e-07 이므로 분산이 다름
t.test(ms$cty ~ ms$class, var.equal=F)
# p-value = 0.05952이므로 0.05보다 커서 차이가 없다고 할 수 있겠다. 


```

```{r}
## 문제 8번
# 멘델의 유전법칙 9 : 3 : 3 : 1 이 맞는지 가설 검정
# 개체수 322, 109, 99, 29

x <- c(322, 109, 99, 29)
chisq.test(x, p=c(9, 3, 3, 1)/16)
# 정규 분포를 따름
t.test(x)
# p-value = 0.1144 이므로 0.05보다 크다 . 그러므로 x는 따른다고 할 수 있다. 

```

```{r}
## 문제 9번 
# women을 이용해 키와 몸무게의 곡선 회귀분석을 통한 회귀식

w <- women

fit  <- lm(height ~ weight + I(weight^2), data = w)
fit  

# -11.7469 + 0.8343 * w - 0.00197 * w^2

```

